name: bo-edrixs-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - arpack=3.8.0=mpi_openmpi_h5a9222f_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - bayesian-optimization=1.4.3=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2023.11.17=py311h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py311h06a4308_0
  - contourpy=1.2.0=py311h9547e67_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - edrixs=0.0.8=py311h1731c80_2
  - entrypoints=0.4=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - fonttools=4.47.0=py311h459d7ec_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h0b41bf4_3
  - ipykernel=6.25.0=py311h92b7b1e_0
  - ipyparallel=8.4.1=py311h06a4308_0
  - ipython=8.20.0=py311h06a4308_0
  - jedi=0.18.1=py311h06a4308_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.5.0=py311h06a4308_0
  - kiwisolver=1.4.5=py311h9547e67_1
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=20_linux64_openblas
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libgomp=13.2.0=h807b86a_3
  - liblapack=3.9.0=20_linux64_openblas
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=hd590300_0
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib-base=3.8.0=py311h54ef318_1
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mpi=1.0=openmpi
  - mpi4py=3.1.5=py311h4267d7f_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py311h06a4308_0
  - numpy=1.26.2=py311h64a7726_0
  - openblas=0.3.25=pthreads_h7a3da1a_0
  - openjpeg=2.4.0=h3ad879b_0
  - openmpi=4.1.6=external_1
  - openssl=3.2.0=hd590300_1
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.3.1=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py311h06a4308_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pyzmq=25.1.0=py311h6a678d5_0
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.3.2=py311hc009520_2
  - scipy=1.11.4=py311h64a7726_0
  - setuptools=68.2.2=py311h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=pyh04b8f61_3
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.3=py311h5eee18b_0
  - tqdm=4.65.0=py311h92b7b1e_0
  - traitlets=5.7.1=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - jax==0.4.30
      - jaxlib==0.4.30
      - ml-dtypes==0.5.3
      - opt-einsum==3.4.0
      - pandas==2.3.3
      - py-bobyqa==1.5.0
      - pytz==2025.2
      - tzdata==2025.2
prefix: /home/raynor/anaconda3/envs/bo-edrixs-env
