name: bo-edrixs-env
channels:
  - conda-forge
  - defaults
dependencies:
  - bayesian-optimization=1.4.3
  - bzip2=1.0.8
  - joblib=1.3.2
  - ipyparallel=8.4.1
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mpi=1.0=openmpi
  - mpi4py=3.1.5
  - mpmath=1.3.0
  - numpy=1.26.2
  - openblas=0.3.25
  - openjpeg=2.4.0
  - openmpi=4.1.6
  - pillow=10.0.1
  - psutil=5.9.0
  - pure_eval=0.2.2
  - python=3.11.5
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - six=1.16.0
  - stack_data=0.2.0
  - sympy=1.12
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - pip:
      - jax==0.4.30
      - jaxlib==0.4.30
      - ml-dtypes==0.5.3
      - opt-einsum==3.4.0
      - pandas==2.3.3
      - py-bobyqa==1.5.0
      - pytz==2025.2
      - tzdata==2025.2